local mode_map = {
  ['n'] = 'NOR',
  ['no'] = 'O-P',
  ['nov'] = 'O-P',
  ['noV'] = 'O-P',
  ['no\22'] = 'O-P',
  ['niI'] = 'N-I',
  ['niR'] = 'N-R',
  ['niV'] = 'N',
  ['nt'] = 'N-T',
  ['v'] = 'VIS',
  ['vs'] = 'V',
  ['V'] = 'V-L',
  ['Vs'] = 'V-L',
  ['\22'] = 'V-B',
  ['\22s'] = 'V-B',
  ['s'] = 'S',
  ['S'] = 'S-L',
  ['\19'] = 'S-B',
  ['i'] = 'INS',
  ['ic'] = 'I-C',
  ['ix'] = 'I-X',
  ['R'] = 'REP',
  ['Rc'] = 'R-C',
  ['Rx'] = 'R-X',
  ['Rv'] = 'V-R',
  ['Rvc'] = 'RVC',
  ['Rvx'] = 'RVX',
  ['c'] = 'CMD',
  ['cv'] = 'EX',
  ['ce'] = 'EX',
  ['r'] = 'R',
  ['rm'] = 'M',
  ['r?'] = 'C',
  ['!'] = 'SH',
  ['t'] = 'TERM',
}

Utils.simple_mode = function ()
  return mode_map[vim.api.nvim_get_mode().mode] or '__'
end
